src/Entity/Measurement.php
<?php

namespace App\Entity;

use App\Repository\MeasurementRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MeasurementRepository::class)]
class Measurement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Location $location = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: '0')]
    private ?string $celsius = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: '0', nullable: true)]
    private ?string $atmosferic_pressure = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: '0', nullable: true)]
    private ?string $rain_drop = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCelsius(): ?string
    {
        return $this->celsius;
    }

    public function setCelsius(string $celsius): self
    {
        $this->celsius = $celsius;

        return $this;
    }

    public function getAtmosfericPressure(): ?string
    {
        return $this->atmosferic_pressure;
    }

    public function setAtmosfericPressure(?string $atmosferic_pressure): self
    {
        $this->atmosferic_pressure = $atmosferic_pressure;

        return $this;
    }

    public function getRainDrop(): ?string
    {
        return $this->rain_drop;
    }

    public function setRainDrop(?string $rain_drop): self
    {
        $this->rain_drop = $rain_drop;

        return $this;
    }
    public function __toString()
    { 
        return $this->getName();
   }
}

src/Entity/Measurements.php
<?php

namespace App\Entity;

use App\Repository\MeasurementsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MeasurementsRepository::class)]
class Measurements
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Location $PlaceID = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: '0')]
    private ?string $temperature = null;

    #[ORM\Column(length: 7)]
    private ?string $Atmosferic_pressure = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $Rain_Drop = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPlaceID(): ?Location
    {
        return $this->PlaceID;
    }

    public function setPlaceID(?Location $PlaceID): self
    {
        $this->PlaceID = $PlaceID;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getTemperature(): ?string
    {
        return $this->temperature;
    }

    public function setTemperature(string $temperature): self
    {
        $this->temperature = $temperature;

        return $this;
    }

    public function getAtmosfericPressure(): ?string
    {
        return $this->Atmosferic_pressure;
    }

    public function setAtmosfericPressure(string $Atmosferic_pressure): self
    {
        $this->Atmosferic_pressure = $Atmosferic_pressure;

        return $this;
    }

    public function getRainDrop(): ?string
    {
        return $this->Rain_Drop;
    }

    public function setRainDrop(string $Rain_Drop): self
    {
        $this->Rain_Drop = $Rain_Drop;

        return $this;
    }
}

src/Form/MeasurementType.php
<?php

namespace App\Form;

use App\Entity\Measurement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MeasurementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date')
            ->add('celsius')
            ->add('atmosferic_pressure')
            ->add('rain_drop')
            ->add('location')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Measurement::class,
        ]);
    }
}

src/Controller/MeasurementController.php
<?php

namespace App\Controller;

use App\Entity\Measurement;
use App\Form\MeasurementType;
use App\Repository\MeasurementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
#[Route('/measurement')]
class MeasurementController extends AbstractController
{
    #[Route('/', name: 'app_measurement_index', methods: ['GET'])]
    #[IsGranted("ROLE_MEASUREMENT_INDEX")]
    public function index(MeasurementRepository $measurementRepository): Response
    {
        return $this->render('measurement/index.html.twig', [
            'measurements' => $measurementRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_measurement_new', methods: ['GET', 'POST'])]
    #[IsGranted("ROLE_MEASUREMENT_NEW")]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $measurement = new Measurement();
        $form = $this->createForm(MeasurementType::class, $measurement,[
            'validation_groups' => ['edit','new'],
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($measurement);
            $entityManager->flush();

            return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('measurement/new.html.twig', [
            'measurement' => $measurement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_measurement_show', methods: ['GET'])]
    #[IsGranted("ROLE_MEASUREMENT_SHOW")]
    public function show(Measurement $measurement): Response
    {
        return $this->render('measurement/show.html.twig', [
            'measurement' => $measurement,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_measurement_edit', methods: ['GET', 'POST'])]
    #[IsGranted("ROLE_MEASUREMENT_EDIT")]
    public function edit(Request $request, Measurement $measurement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MeasurementType::class, $measurement,[
            'validation_groups' => ['edit','new'],
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('measurement/edit.html.twig', [
            'measurement' => $measurement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_measurement_delete', methods: ['POST'])]
    #[IsGranted("ROLE_MEASUREMENT_DELETE")]
    public function delete(Request $request, Measurement $measurement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$measurement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($measurement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/measurement/_delete_form.html.twig
<form method="post" action="{{ path('app_measurement_delete', {'id': measurement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ measurement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/measurement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/measurement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Measurement{% endblock %}

{% block body %}
    <h1>Edit Measurement</h1>

    {{ include('measurement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_measurement_index') }}">back to list</a>

    {{ include('measurement/_delete_form.html.twig') }}
{% endblock %}

templates/measurement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Measurement index{% endblock %}

{% block body %}

    <h1>Measurement index</h1>

  
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Celsius</th>
                <th>Atmosferic_pressure</th>
                <th>Rain_drop</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for measurement in measurements %}
            <tr>
                <td>{{ measurement.id }}</td>
                <td>{{ measurement.date ? measurement.date|date('Y-m-d') : '' }}</td>
                <td>{{ measurement.celsius }}</td>
                <td>{{ measurement.atmosfericPressure }}</td>
                <td>{{ measurement.rainDrop }}</td>
                <td>
                {% if is_granted('ROLE_MEASUREMENT_SHOW')%}
                    <a href="{{ path('app_measurement_show', {'id': measurement.id}) }}">show</a>
                    {% endif %}
                {% if is_granted('ROLE_MEASUREMENT_EDIT')%}
                    <a href="{{ path('app_measurement_edit', {'id': measurement.id}) }}">edit</a>
                     {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_granted('ROLE_MEASUREMENT_NEW')%}
    <a href="{{ path('app_measurement_new') }}">Create new</a>
    {% endif %}
      <h2>Routing</h2>
        <ul>
    <li> <a href= "{{ path("measurement") }}">Measurement</a></li>
    <li> <a href= "{{ path("location") }}">Location</a></li>
        <li> <a href= "{{ path("app_logout") }}"> Logout </a></li>
    </ul>
{% endblock %}

templates/measurement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Measurement{% endblock %}

{% block body %}
    <h1>Create new Measurement</h1>

    {{ include('measurement/_form.html.twig') }}

    <a href="{{ path('app_measurement_index') }}">back to list</a>
{% endblock %}

templates/measurement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Measurement{% endblock %}

{% block body %}
    <h1>Measurement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ measurement.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ measurement.date ? measurement.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Celsius</th>
                <td>{{ measurement.celsius }}</td>
            </tr>
            <tr>
                <th>Atmosferic_pressure</th>
                <td>{{ measurement.atmosfericPressure }}</td>
            </tr>
            <tr>
                <th>Rain_drop</th>
                <td>{{ measurement.rainDrop }}</td>
            </tr>
        </tbody>
    </table>
    
    <a href="{{ path('app_measurement_index') }}">back to list</a>
    {% if is_granted('ROLE_MEASUREMENT_EDIT')%}
    <a href="{{ path('app_measurement_edit', {'id': measurement.id}) }}">edit</a>
    {% endif %}
    {% if is_granted('ROLE_MEASUREMENT_DELETE')%}
    {{ include('measurement/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}